apiVersion: tekton.dev/v1alpha1
kind: StepAction
metadata:
  name: cache-upload
  annotations:
    tekton.dev/pipelines.minVersion: "0.56.0"
    tekton.dev/tags: "cache"
spec:
  params:
    - name: patterns
      description: |
        Regular expression to select files to include to compute the hash.
        For example, in the case of a Go project, you can use `go.mod` for this, so the value would be "**/go.sum" (to work with possible sub go modules as well).
      type: array
    - name: target
      description: |
        The target from where the cache should be uploaded. It's a URI with the scheme defining the "provider". In addition, one can add a {{hash}} variable to use the computed hash in the reference (oci image tags, path in s3, …)
        Currently supported:
        - oci:// (e.g. oci://quay.io/vdemeester/go-cache:{{hash}}
        - s3:// (e.g. s3://
      type: string
    - name: cachePath
      description: |
        Path where to extract the cache content.
        It can refer any folder, backed by a workspace or a volume, or nothing.
      type: string
    - name: workingdir
      description: |
        The working dir from where the files patterns needs to be taken
      type: string
    - name: insecure
      description: |
        Whether to use insecure mode for fetching the cache
      type: string
      default: "false"
  results: # Any result to "publish" ?
    - name: fetched
      description: |
        Whether a cache was fetched or not (true/false). This step won't fail if it didn't manage to fetch cache. This results allows the next step to act whether something was fetched or not.
  env:
    - name: PARAM_TARGET
      value: $(params.target)
    - name: PARAM_CACHE_PATH
      value: $(params.cachePath)
    - name: PARAM_WORKINGDIR
      value: $(params.workingdir)
    - name: PARAM_INSECURE
      value: $(params.insecure)
  # FIXME: use a released version once something is released :)
  image: ghcr.io/openshift-pipelines/tekton-caches/cache:latest
  args: ["$(params.patterns[*])"]
  script: |
    #!/bin/sh

    PATTERN_FLAGS=""
    echo "Patterns: $*"
    for p in $*; do
      PATTERN_FLAGS="${PATTERN_FLAGS} --pattern ${p}"
    done

    set -ex
    /ko-app/cache upload ${PATTERN_FLAGS} \
                        --target ${PARAM_TARGET} \
                        --folder ${PARAM_CACHE_PATH} \
                        --insecure ${PARAM_INSECURE} \
                        --workingdir ${PARAM_WORKINGDIR}
