---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: pipeline-go
spec:
  params:
    - name: repo_url
      type: string
    - name: revision
      type: string
    - name: registry
      type: string
    - name: buildCommand
      type: string
      default: go build -v .
  workspaces:
    - name: source
  tasks:
    - displayName: Build go application
      name: build-task
      workspaces:
        - name: source
          workspace: source
      taskSpec:
        workspaces:
          - name: source
        params:
          - name: buildCommand
            default: $(params.buildCommand)
        steps:
          - name: create-repo
            image: cgr.dev/chainguard/go
            script: |
              mkdir -p $(workspaces.source.path)/repo
              chmod 777 $(workspaces.source.path)/repo
          - name: fetch-repo
            ref:
              resolver: http
              params:
                - name: url
                  value: https://raw.githubusercontent.com/tektoncd/catalog/main/stepaction/git-clone/0.1/git-clone.yaml
            params:
              - name: output-path
                value: $(workspaces.source.path)/repo
              - name: url
                value: $(params.repo_url)
              - name: revision
                value: $(params.revision)
          - name: fetch-cache
            ref:
              resolver: http
              params:
                - name: url
                  value: https://raw.githubusercontent.com/openshift-pipelines/tekton-caches/main/tekton/cache-fetch.yaml
            params:
              - name: patterns
                value:
                  - "**.go"
                  - "**go.sum"
              - name: source
                value: oci://$(params.registry)/cache-go:{{hash}}
              - name: cachePath
                value: $(workspaces.source.path)/cache
              - name: workingdir
                value: $(workspaces.source.path)/repo
          - image: cgr.dev/chainguard/go
            workingDir: $(workspaces.source.path)/repo
            name: noop-task
            env:
              - name: GOCACHE
                value: $(workspaces.source.path)/cache/gocache
              - name: GOMODCACHE
                value: $(workspaces.source.path)/cache/gomodcache
            script: |
              set -x
              git config --global --add safe.directory $(workspaces.source.path)/repo
              $(params.buildCommand)
              du -shk $GOPATH
              du -shk $GOMODCACHE
          - name: cache-upload
            ref:
              resolver: http
              params:
                - name: url
                  value: https://raw.githubusercontent.com/openshift-pipelines/tekton-caches/main/tekton/cache-upload.yaml
            params:
              - name: patterns
                value:
                  - "**.go"
                  - "**go.sum"
              - name: target
                value: oci://$(params.registry)/cache-go:{{hash}}
              - name: cachePath
                value: $(workspaces.source.path)/cache
              - name: workingdir
                value: $(workspaces.source.path)/repo
