---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: pipelinerun-oci-
spec:
  pipelineRef:
    name: pipeline
  params:
    - name: repo_url
      value: https://github.com/chmouel/go-helloworld
    - name: revision
      value: main
      # This uses S3 bucket  to upload Caches
    - name: registry
      value: oci://docker.io/<username>
    - name: buildCommand
      value: go build -v ./
    - name: image
      value: golang:1.21
  workspaces:
    - name: cred
      secret:
        secretName: regcred
    - name: source
      emptyDir: {}
