on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

name: build-test-publish

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - name: Set up Go
      uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
      with:
        go-version: "1.21"
    - run: go env
    - name: go build
      run: go build -v ./...
    - name: go test
      run: go test -v ./...

  # e2e:
  #   name: e2e tests
  #   runs-on: ubuntu-latest
  #   needs: [ build ]
  # 
  #   steps:
  #   - uses: ko-build/setup-ko@v0.6
  #   - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
  #   - uses: chainguard-dev/actions/setup-kind@main
  #     with:
  #       k8s-version: v1.23.x
  #   - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
  #     with:
  #       go-version: "1.21"
  #   - uses: vdemeester/setup-tektoncd@main
  #     with:
  #       pipeline: v0.40.x
  #       pipeline-feature-flags: '{"enable-api-fields": "alpha"}'
  #   - name: install manual-approval-gate custom task
  #     run: |
  #       # FIXME: remove this once >= 0.41.x
  #       kubectl apply -f https://storage.googleapis.com/tekton-releases/pipeline/previous/v0.40.2/resolvers.yaml
  #       ko apply --local -f config/
        
  publish:
    name: publish latest
    runs-on: ubuntu-latest
    needs: [ build ]

    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      id-token: write
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
      with:
        go-version: "1.21"
    - id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ github.repository }}/cache
        flavor: |
          latest=${{ github.event_name != 'pull_request' }}
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: ko-build/setup-ko@v0.6
    - run: |
        ko publish --push=${{ github.event_name != 'pull_request' }} --base-import-paths ./cmd/cache
